### ISSUE TITLE
Project Life cycle investigation

### ISSUE THREAD

**Issue by timack** [159356-1702-Extramural/capstone#4]

**Comment by sumnerfit** [comment]
**Initial findings on project lifecycle management.**

For textbook : "Exploring Interface Design" by Marc Silver
Why have the process:
- Increases efficiency
- Produces consistantly better results
- Validates User Interface Design Function 

Comments on Agile 
- includes eXtreme Programming, Adaptive Software Development, Scrum, Crystal
- uses an iterative approach
- agile technologies are intended for situations where either the project requirements or the technology is not well known or evolving. They are also used when a client is not sure if the project will be approved for full development.

Comments on Waterfall
- includes standard Waterfall model, Repeating Waterfall, Spiral Model
- uses  

Table 3-1 Page 54
![agilevwaterfall](https://user-images.githubusercontent.com/22135017/28508731-f476cdbe-7090-11e7-920c-b1d8031b2c57.jpg)

I would suggest a repeating waterfall model.  Its not modern or in vogue but I think it'll allow us to smash out the project in the required timeframe.

- Project Planning Stage
- Requirements Deninition
- System Design
- Implementation
- Integration and Testing (loops back to System Design) 
- Installation and deployment
- Maintenace

Which brings me to timeframes.

**Comment by sumnerfit** [comment]
Week 1
Week 
Week

**Comment by sumnerfit** [comment]
Whatever model we use, we are 2 weeks in and should formalise the full 12 weeks to make sure we get and stay ahead of schedule.

This is a quick example of timeframes to get people talking.

Week 1  - Done
Week 2
- Agree on software and platform
- Requirement definitions (gameplay concepts agreed)

Week 3
- Start loop -> System design / Implementation / Integrate and test
- Either as a weekly or fortnightly loop
- If weekly we get 8 loops but times will be pushed
- If fortnightly we get 4 loops to iterate over the work

Week 4  - Report Due / loop
Week 5 - loop
Week 6 - loop
Week 7 - loop
Week 8  - Report Due / loop
Week 9 - loop / integtrate extra features
Week 10 - loop / integtrate extra features
Week 11 - Installation and deployment
Week 12  - Report Due
Week 13

**Comment by timack** [comment]
Yep - I think `Requirement definitions` i will be critical bit in determining if we hit our deadlines. Particularly for week 8. I think we need to decide what requirements would make up a minimum viable product. ie. anything not absolutely critical we leave until later. If we're ahead of schedule we can prioritise and pull in 'nice-to-haves'...

I think we aim for a weekly loop considering the timeframe.

**Comment by sumnerfit** [comment]
Also , looking into use cases, there is a requirement that we describe when each requirement will be supported so the goals of all the loops (when features are added) will need to be created before the week four report.

**Comment by timack** [comment]
Right, so can we turn each requirement into an 'issue' and then to can link it to a Milestone. And the Milestones can represent the end each Loop. If we get ahead we can move things from future loops in the current loop, if we get behind we may have to move things from the current loop in to a future loop. I think the key thing is that we make sure we allow plenty of contingency for some slippage.

**Comment by timack** [comment]
This one looks interesting: https://www.zenhub.com/ and works well with GitHub.

**Comment by sumnerfit** [comment]
Waterfall as it is described in a lot of places tends to be seen as one person doing work, passing it to the next person who then does their parts.  We'll all be working on pieces together so we technically won't be using waterfall.
The repeating waterfall model I posted has a lot in keeping with a SCRUMM mentality.
The first sections are collaborative, getting the processes in place and the game design prepared.  We should have the Release Backlog ready (All the things to do to have the game complete) which in Zenhub are found in the Boards Tab.
Each weekly loop in SCRUMM terms is called a sprint.  We decide what items from the Release Backlog can be done in this Sprint, assign them to each person.  There is supposed to be a daily meeting where we ask 3 questions: 
What have you done since last scrumm meeting?
What do you plan to do before the next scrumm meeting?
What obstacles stand in your way to finish this task?
We can do this on each catchup session.

At the end of the Sprint (week), have a sprint review meeting to demonstrate what has been achieved and then start another Sprint assigning work.

**Comment by timack** [comment]
I don't know if daily meetings will be feasible. But I like the sounds of the rest of it! I think we need a fairly agile process due to the tight times lines and to be able to adapt evolving requirements.

**Comment by sumnerfit** [comment]
Those questions would be good at each meeting (3 per week)

**Comment by timack** [comment]
Yep perfect.
